apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: joshsizer
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: joshsizer
      githubAPICredentialsFrom:
        secretRef:
          name: joshsizer-runner
