apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: joshsizer-blogposts-generator
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: joshsizer/blogposts-generator
      githubAPICredentialsFrom:
        secretRef:
          name: joshsizer-runners
