---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    installCRDs: true
    prometheus:
      enabled: false
